catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('book/<uuid:pk>/return/', views.mark_returned, name='book-return'),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
    path('borrowed/', views.AllBorrowedBooksListView.as_view(), name='all-borrowed'),
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),  # Trỏ đến app catalog
    path('', RedirectView.as_view(url='catalog/')),  # Chuyển hướng trang chủ về catalog/
    path('accounts/', include('django.contrib.auth.urls')), # Django se tu dong tao cac trang co URL: accounts/login, accounts/logout, /accounts/password_change/, /password_reset/
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
import uuid
from datetime import date
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from . import constants


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=constants.GENRE_NAME_MAX_LENGTH,
        help_text=_('Enter a book genre (e.g. Science Fiction)')
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=constants.BOOK_TITTLE_MAX_LENGTH)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=constants.BOOK_SUMMARY_MAX_LENGTH,
        help_text=_('Enter a brief description of the book')
    )
    isbn = models.CharField(
        'ISBN',
        max_length=constants.BOOK_ISBN_MAX_LENGTH,
        unique=True,
        help_text=_(
            '13 Character '
            '<a href="https://www.isbn-international.org/content/what-isbn">'
            'ISBN number</a>'))
    genre = models.ManyToManyField(
        Genre, help_text=_('Select a genre for this book'))

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:constants.DISPLAYED_GENRE_MAX])
    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """Model representing a specific copy of a book
    (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text=_('Unique ID for this particular bookacross whole library'))
    book = models.ForeignKey('Book', on_delete=models.RESTRICT)
    imprint = models.CharField(
        max_length=constants.BOOKINSTANCE_IMPRINT_MAX_LENGTH)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    status = models.CharField(
        max_length=constants.BOOKINSTANCE_STATUS_MAX_LENGTH,
        choices=constants.LoanStatus.choices,
        blank=True,
        default=constants.LoanStatus.MAINTENANCE,
        help_text=_('Book availability'),
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'
    
    @property
    def is_overdue(self):
        return self.due_back and date.today() > self.due_back


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(
        max_length=constants.AUTHOR_FIRSTNAME_MAX_LENGTH)
    last_name = models.CharField(
        max_length=constants.AUTHOR_LASTNAME_MAX_LENGTH)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

catalog/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstance


class RenewBookModelForm(ModelForm): # Cach 2: Model Form
    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        
        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        
        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))
        
        # Remember to always return the cleaned data.
        return data
    
    class Meta:
        model = BookInstance
        fields = ['due_back']
        labels = {'due_back': _('Renewal date')}
        help_texts = {'due_back': _('Enter a date between now and 4 weeks (default 3).')}

catalog/views.py
import datetime
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views import View, generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import permission_required, login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from catalog.models import Book, Author, BookInstance, Genre
from catalog.forms import RenewBookModelForm
from . import constants


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()

    # Available books (status = 'a')
    num_instances_available = BookInstance.objects.filter(
        status=constants.LoanStatus.AVAILABLE
    ).count()
    # The 'all()' is implied by default.
    num_authors = Author.objects.count()
    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    # your own name for the list as a template variable
    context_object_name = 'book_list'
    # Specify your own templatename/location
    template_name = 'catalog/book_list.html'
    paginate_by = constants.BOOKS_PER_PAGE_MAX

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        return context


class BookDetailView(generic.DetailView):  # Cach 1: Class-Based Views
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['STATUS_AVAILABLE'] = constants.LoanStatus.AVAILABLE.value
        context['STATUS_MAINTENANCE'] = constants.LoanStatus.MAINTENANCE.value
        return context


def book_detail_view(request, pk):  # Cach 2: Function-Based Views
    book = get_object_or_404(Book, pk=pk)
    return render(request, 'catalog/book_detail.html', context={'book': book})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = constants.BOOKS_PER_PAGE_MAX

    def get_queryset(self):
        return BookInstance.objects.filter(
                borrower=self.request.user
            ).filter(status__exact=constants.LoanStatus.ON_LOAN.value
            ).order_by('due_back')


class AllBorrowedBooksListView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(
            status__exact=constants.LoanStatus.ON_LOAN.value).order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned')
def mark_returned(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    book_instance.status = constants.LoanStatus.AVAILABLE.value
    book_instance.borrower = None
    book_instance.due_back = None
    book_instance.save()
    return redirect('my-borrowed')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the modeldue_back field)
            book_instance.due_back = form.cleaned_data['due_back']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed'))
    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={'due_back': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorListView(generic.ListView):
    model = Author
    content_object_name = 'author_list'
    template_name = 'catalog/author_list.html'
    paginate_by = constants.AUTHORS_PER_PAGE_MAX


class StaffRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff


class AuthorCreate(StaffRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    initial = {'date_of_death': constants.INITIAL_DEADTH_DATE_OF_AUTHOR}
    success_url = reverse_lazy('authors')


class AuthorUpdate(StaffRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
    success_url = reverse_lazy('authors')


class AuthorDelete(StaffRequiredMixin, DeleteView):
    model = Author
    success_url = reverse_lazy('authors')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Delete Author" %}</h1>

    <p>
        {% blocktrans with author_name=author %}
            Are you sure you want to delete the author: {{ author_name }}?
        {% endblocktrans %}
    </p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="{% trans 'Yes, delete.' %}">
    </form>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
  <h1>{% trans "Author List" %}</h1>

  {# Button for creating a new author only for staff #}
  {% if user.is_authenticated and user.is_staff %}
    <p>
      <a href="{% url 'author-create' %}" class="btn btn-primary">
        {% trans "Create new author" %}
      </a>
    </p>
  {% endif %}
  
  {% if author_list %}
    <ul>
      {% for author in author_list %}
        <li>
          {% if user.is_staff %}
            <a href="{% url 'author-update' author.id %}">
              {{ author.last_name }}, {{ author.first_name }}
            </a>
          {% else %}
            {{ author.last_name }}, {{ author.first_name }}
          {% endif %}

        <br>
        {% trans "Birth" %}: {{ author.date_of_birth|date:"d/m/Y" }},
        {% trans "Death" %}: 
        {% if author.date_of_death %}
            {{ author.date_of_death|date:"d/m/Y" }}
        {% else %}
            {% trans "N/A" %}
        {% endif %}        
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no authors in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load static %}

{% block content %}
    <h1>{% blocktrans with book_title=book.title %}Title: {{ book_title }}{% endblocktrans %}</h1>

    <p>
        <strong>{% trans "Author:" %}</strong>
        <a href="">{{ book.author }}</a>
    </p> <!-- author detail link not yet defined -->

    <p>
        <strong>{% trans "Summary:" %}</strong> {{ book.summary }}
    </p>

    <p>
        <strong>{% trans "ISBN:" %}</strong> {{ book.isbn }}
    </p>

    <p>
        <strong>{% trans "Language:" %}</strong> {{ book.language }}
    </p>

    <p>
        <strong>{% trans "Genre:" %}</strong> {{ book.display_genre }}
    </p>

    <div class="bookinstance-container">
        <h4>{% trans "Copies" %}</h4>
        
        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == STATUS_AVAILABLE %}text-success{% elif copy.status == STATUS_MAINTENANCE %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != STATUS_AVAILABLE %}
                <p>
                    <strong>{% trans "Due to be returned:" %}</strong> {{ copy.due_back }}
                </p>
            {% endif %}

            <p>
                <strong>{% trans "Imprint:" %}</strong> {{ copy.imprint }}
            </p>

            <p class="text-muted">
                <strong>{% trans "Id:" %}</strong> {{ copy.id }}
            </p>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Book List" %}</h1>

    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
                    {% blocktrans with author=book.author %}
                        ({{ author }})
                    {% endblocktrans %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books in the library." %}</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}

    <h1>{% trans "Renew:" %} {{ book_instance.book.title }}</h1>
    <p>{% trans "Borrower" %}: {{ book_instance.borrower }}</p>

    <p {% if book_instance.is_overdue %} class="text-danger"{% endif %}>
        {% trans "Due date" %}: {{ book_instance.due_back }}
    </p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="{% trans 'Submit' %}">
    </form>

{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% trans "Borrowed books" %}</h1>

    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a>
                    ({{ bookinst.due_back }})
                </li>

                {% if perms.catalog.can_mark_returned %}
                    <a href="{% url 'book-return' bookinst.pk %}">{% trans "Return book" %}</a>
                    <a href="{% url 'renew-book-librarian' bookinst.pk %}">{% trans "Renew" %}</a>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}